### ISSUE TITLE
Checked status doesn't persist when I refresh

### ISSUE THREAD

**Issue by kknape** [whereispolaris/firebase-application#35]
Hi, I noticed when testing the congrats message - that if I check an item as complete, then refresh the page, the Checked box doesn't persist. It becomes unchecked. Maybe the checked status isn't being captured in the db.

**Comment by whereispolaris** [comment]
I'm going to work on this one now. I think we need to add something like checked = true and send that information to firebase.

**Comment by whereispolaris** [comment]
Checkboxes seem to be very difficult to manipulate, so I think we should use buttons instead.

**Comment by kknape** [comment]
re-opened until we have Done status captured.
